2850 #!/usr/bin/perl -w
2851 
2852 # Generate vectors.S, the trap/interrupt entry points.
2853 # There has to be one entry point per interrupt number
2854 # since otherwise there's no way for trap() to discover
2855 # the interrupt number.
2856 
2857 print "# generated by vectors.pl - do not edit\n";
2858 print "# handlers\n";
2859 print ".globl alltraps\n";
2860 for(my $i = 0; $i < 256; $i++){
2861     print ".globl vector$i\n";
2862     print "vector$i:\n";
2863     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
2864         print "  pushl \$0\n";
2865     }
2866     print "  pushl \$$i\n";
2867     print "  jmp alltraps\n";
2868 }
2869 
2870 print "\n# vector table\n";
2871 print ".data\n";
2872 print ".globl vectors\n";
2873 print "vectors:\n";
2874 for(my $i = 0; $i < 256; $i++){
2875     print "  .long vector$i\n";
2876 }
2877 
2878 # sample output:
2879 #   # handlers
2880 #   .globl alltraps
2881 #   .globl vector0
2882 #   vector0:
2883 #     pushl $0
2884 #     pushl $0
2885 #     jmp alltraps
2886 #   ...
2887 #
2888 #   # vector table
2889 #   .data
2890 #   .globl vectors
2891 #   vectors:
2892 #     .long vector0
2893 #     .long vector1
2894 #     .long vector2
2895 #   ...
2896 
2897 
2898 
2899 
